# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfiles',
            name='filename',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='myfiles',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='myfiles',
            name='time_of_uploading',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='myfiles',
            name='type_of_file',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
