# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20160701_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfiles',
            name='time_of_uploading',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
