# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20160701_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfiles',
            name='new_file',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
